export const siteConfig = {
  name: "Swarms AI — Multi-Agent Framework & Agent Marketplace",
  description:
    "Swarms is the enterprise-grade multi-agent framework for building, deploying, and scaling AI agents in Python and Rust — with a hosted agent API and a marketplace to buy and sell agents, prompts, tools, and skills. One platform from your first agent to production swarms.",
  url: "https://swarms.ai",
  ogImage: "/seo_image.jpg", // Use seo_image.jpg for Open Graph and SEO
  logo: "/logo.svg", // Use logo.svg for logo and favicon
  seoBackground: "/seo_image.jpg", // Custom field for SEO background
  links: {
    github: "https://github.com/kyegomez/swarms",
    docs: "https://docs.swarms.world",
    marketplace: "https://swarms.world",
  },
  keywords: [
    // Primary
    "agent framework",
    "multi-agent framework",
    "AI agent framework",
    "agent marketplace",
    "AI agent marketplace",
    "skills marketplace",
    "agent skills marketplace",
    "prompt marketplace",
    "prompts marketplace",
    "agent orchestration",
    "multi-agent systems",
    "multi-agent orchestration",
    "agent infrastructure",
    "agent economy",
    // Marketplace intent
    "buy AI agents",
    "sell AI agents",
    "buy prompts",
    "sell prompts",
    "AI skills",
    "agent skills",
    "agent tools marketplace",
    "prompt library",
    "prompt engineering",
    "agent templates",
    // Platform & runtime
    "agent API",
    "agent runtime",
    "hosted agent API",
    "agent deployment",
    "agent cloud platform",
    "enterprise AI agents",
    "production AI agents",
    "autonomous agents",
    "AI agents",
    "LLM agents",
    "LLM orchestration",
    "AI workflow automation",
    "business process automation",
    // Framework specifics
    "python agent framework",
    "rust agent framework",
    "open source agent framework",
    "agent swarm",
    "swarm intelligence",
    "hierarchical swarm",
    "sequential workflow",
    "concurrent workflow",
    "graph workflow",
    "mixture of agents",
    "group chat agents",
    "agent registry",
    "agent-to-agent communication",
    "multi-agent memory",
    "agent simulation environments",
    "MCP integration",
    "structured outputs",
    "RAG integration",
    // Brand
    "swarms",
    "swarms ai",
    "swarms framework",
    "swarms python",
    "swarms rust",
    "swarms api",
    "swarms marketplace",
    "swarms cloud",
    "swarms docs",
    "kyegomez",
    // Comparisons & ecosystem
    "langchain alternative",
    "autogen alternative",
    "crewai alternative",
    "openai agents",
    "anthropic agents",
    "claude agents",
    "gpt agents",
    // Verticals
    "finance agents",
    "healthcare agents",
    "research agents",
    "marketing agents",
    "medical swarm",
    "finance swarm",
  ],
  company: {
    name: "Swarms AI",
    description:
      "Swarms AI builds the enterprise-grade multi-agent framework, hosted agent API, and agent marketplace powering the agent economy.",
    foundingDate: "2023",
    founders: [
      {
        name: "Kye Gomez",
        url: "https://github.com/kyegomez",
      },
    ],
    address: {
      addressCountry: "US",
    },
  },
}
