export const siteConfig = {
  name: "Swarms AI — Multi-Agent Framework & Agent Marketplace",
  description:
    "Swarms is the enterprise-grade multi-agent framework for building, deploying, and scaling AI agents in Python and Rust — with a hosted agent API and a marketplace to buy and sell agents, prompts, tools, and skills. One platform from your first agent to production swarms.",
  url: "https://swarms.ai",
  ogImage: "/seo_image.jpg", // Use seo_image.jpg for Open Graph and SEO
  logo: "/logo.svg", // Use logo.svg for logo and favicon
  seoBackground: "/seo_image.jpg", // Custom field for SEO background
  links: {
    github: "https://github.com/kyegomez/swarms",
    docs: "https://docs.swarms.world",
    marketplace: "https://swarms.world",
  },
  keywords: [
    // Primary
    "agent framework",
    "multi-agent framework",
    "AI agent framework",
    "agent marketplace",
    "AI agent marketplace",
    "skills marketplace",
    "agent skills marketplace",
    "prompt marketplace",
    "prompts marketplace",
    "agent orchestration",
    "multi-agent systems",
    "multi-agent orchestration",
    "agent infrastructure",
    "agent economy",
    // Marketplace intent
    "buy AI agents",
    "sell AI agents",
    "buy prompts",
    "sell prompts",
    "AI skills",
    "agent skills",
    "agent tools marketplace",
    "prompt library",
    "prompt engineering",
    "agent templates",
    // Platform & runtime
    "agent API",
    "agent runtime",
    "hosted agent API",
    "agent deployment",
    "agent cloud platform",
    "enterprise AI agents",
    "production AI agents",
    "autonomous agents",
    "AI agents",
    "LLM agents",
    "LLM orchestration",
    "AI workflow automation",
    "business process automation",
    // Framework specifics
    "python agent framework",
    "rust agent framework",
    "open source agent framework",
    "agent swarm",
    "swarm intelligence",
    "hierarchical swarm",
    "sequential workflow",
    "concurrent workflow",
    "graph workflow",
    "mixture of agents",
    "group chat agents",
    "agent registry",
    "agent-to-agent communication",
    "multi-agent memory",
    "agent simulation environments",
    "MCP integration",
    "structured outputs",
    "RAG integration",
    // Brand
    "swarms",
    "swarms ai",
    "swarms framework",
    "swarms python",
    "swarms rust",
    "swarms api",
    "swarms marketplace",
    "swarms cloud",
    "swarms docs",
    "kyegomez",
    // Comparisons & ecosystem
    "langchain alternative",
    "autogen alternative",
    "crewai alternative",
    "openai agents",
    "anthropic agents",
    "claude agents",
    "gpt agents",
    // Verticals
    "finance agents",
    "healthcare agents",
    "research agents",
    "marketing agents",
    "medical swarm",
    "finance swarm",
  ],
  company: {
    name: "Swarms AI",
    description:
      "Swarms AI builds the enterprise-grade multi-agent framework, hosted agent API, and agent marketplace powering the agent economy.",
    foundingDate: "2023",
    founders: [
      {
        name: "Kye Gomez",
        url: "https://github.com/kyegomez",
      },
    ],
    address: {
      addressCountry: "US",
    },
  },
}

// Simplified Chinese site config for the /zh route tree. Keywords are native
// Baidu search terms, not translations of the English keyword list.
export const zhSiteConfig = {
  name: "Swarms AI - 企业级多智能体框架与智能体市场",
  description:
    "Swarms 是企业级多智能体框架，支持用 Python 和 Rust 构建、部署和扩展 AI 智能体，提供托管智能体 API 以及交易智能体、提示词、工具与技能的市场。从第一个智能体到生产级智能体集群，一个平台全部搞定。",
  url: `${siteConfig.url}/zh`,
  keywords: [
    // 核心
    "智能体框架",
    "多智能体框架",
    "多智能体系统",
    "AI智能体",
    "AI智能体开发",
    "智能体编排",
    "多智能体编排",
    "智能体基础设施",
    // 市场
    "智能体市场",
    "AI智能体平台",
    "提示词市场",
    "提示词工程",
    "智能体模板",
    "购买AI智能体",
    // 平台与运行时
    "智能体API",
    "托管智能体API",
    "智能体部署",
    "智能体云平台",
    "企业级AI智能体",
    "生产级AI智能体",
    "自主智能体",
    "大模型智能体",
    "LLM智能体",
    "LLM编排",
    "AI工作流自动化",
    // 框架细分
    "Python智能体框架",
    "Rust智能体框架",
    "开源智能体框架",
    "群体智能",
    "多智能体协作",
    "智能体间通信",
    "MCP协议",
    "MCP集成",
    "RAG集成",
    "结构化输出",
    // 品牌
    "swarms",
    "swarms中文",
    "swarms框架",
    "swarms教程",
    "LangChain替代品",
  ],
}
